// Generated by CoffeeScript 1.3.3
(function() {
  var bind_keyboard;

  bind_keyboard = function() {
    return keypress.register_combo();
  };

  $(function() {
    return bind_keyboard();
  });

}).call(this);
